import {
  FacebookSquare as Facebook,
  Instagram,
  Whatsapp,
} from "@styled-icons/boxicons-logos";
import { type NextPage } from "next";
import Head from "next/head";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Ike Consertos</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/logo-ike-consertos-3-ico.ico" />
      </Head>
      <main className="bg-02 relative flex h-[100svh] items-center justify-center overflow-y-auto overflow-x-hidden bg-black">
        <div
          className="absolute top-0 
          left-[10vw] 
          z-10 
          h-[320px] 
          w-[520px] 
          bg-gradient-to-r 
          from-violet-900 
          via-blue-500 
          to-rose-900 
          blur-[130px]"
        />
        <div
          className="absolute bottom-0 
          right-[20vw] 
          z-10 
          h-[320px] 
          w-[520px] 
          bg-gradient-to-r 
          from-violet-900 
          via-cyan-400 
          to-blue-900 
          blur-[130px]"
        />
        <div
          className="absolute 
          top-0 
          right-[10vw] 
          z-10 
          h-[320px] 
          w-[520px] 
          bg-gradient-to-r 
          from-violet-800 
          via-violet-500 
          to-violet-800 
          blur-[130px]"
        />
        <div className="relative z-20  mt-14 flex w-full flex-col items-center bg-white px-4 py-8 pt-20 sm:w-fit sm:max-w-[520px] sm:rounded-xl sm:border sm:px-5 sm:py-8 sm:pt-20">
          <div className="absolute top-0 h-28 w-28 shrink-0 -translate-y-1/2 overflow-hidden rounded-full">
            {/* eslint-disable-next-line @next/next/no-img-element */}
            <img
              className="object-cover"
              src="/logo-ike-consertos-3.png"
              alt="Logo do Ike Consertos"
            />
          </div>
          <div className="mb-4 flex flex-col items-center">
            <div className="relative">
              <h1 className="relative font-tesla text-4xl font-black uppercase leading-6 text-neutral-800">
                Ike
              </h1>
              {/* <span className="absolute bottom-0 left-full block truncate text-sm text-neutral-800">
                Michel Dias
              </span> */}
            </div>
            <h2 className="mb-4 font-semibold text-neutral-700">
              assistência técnica
            </h2>
            <p className="text-sm text-neutral-900">
              Faço consertos e vendas de celular na região de Canudos/NH, para
              fazer um orçamento, entre em contato 👇
            </p>
          </div>
          <div className="flex w-full flex-col gap-4 text-white">
            <div className="relative">
              {/* <div className="absolute inset-0 z-10 h-full w-full translate-x-2 translate-y-2 rounded-md bg-black" /> */}
              <a
                href="https://api.whatsapp.com/send?phone=555189071588&text=Oi,%20gostaria%20de%20fazer%20um%20or%C3%A7amento,%20me%20chamo%20"
                target="_blank"
              >
                <button className="relative z-20 flex w-full grow items-center justify-center rounded-md bg-white bg-gradient-to-r from-green-500 to-green-400 p-4">
                  <i className="absolute left-4 top-1/2 -translate-y-1/2">
                    <Whatsapp width={32} height={32} />
                  </i>
                  <span className="block">Whatsapp</span>
                </button>
              </a>
            </div>
            <div className="relative">
              {/* <div className="absolute inset-0 z-10 h-full w-full translate-x-1.5 translate-y-1.5 rounded-md bg-gradient-to-l from-pink-600 to-violet-600" /> */}
              <a href="https://www.instagram.com/ike.cell" target="_blank">
                <button className="relative z-20 flex w-full grow items-center justify-center rounded-md bg-white bg-gradient-to-r from-orange-400 via-pink-500 to-violet-500 p-4">
                  <i className="absolute left-4 top-1/2 -translate-y-1/2">
                    <Instagram width={32} height={32} />
                  </i>
                  <span className="block">Instagram</span>
                </button>
              </a>
            </div>
            <div className="relative">
              {/* <div className="absolute inset-0 z-10 h-full w-full translate-x-1.5 translate-y-1.5 rounded-md bg-gradient-to-l from-blue-700 to-blue-900" /> */}
              <a
                href="https://www.facebook.com/profile.php?id=100090579578848"
                target="_blank"
              >
                <button className="relative z-20 flex w-full grow items-center justify-center rounded-md bg-white bg-gradient-to-r from-blue-700 to-blue-500 p-4">
                  <i className="absolute left-4 top-1/2 -translate-y-1/2">
                    <Facebook width={32} height={32} />
                  </i>
                  <span className="block">Facebook</span>
                </button>
              </a>
            </div>
          </div>
        </div>
      </main>
    </>
  );
};

export default Home;
