import {
  FacebookSquare as Facebook,
  Instagram,
  Whatsapp
} from "@styled-icons/boxicons-logos";
import { type NextPage } from "next";
import Head from "next/head";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-01 flex h-screen items-center justify-center overflow-auto bg-neutral-900">
        <div className="relative flex flex-col items-center rounded-3xl border border-black bg-white p-12 pt-16">
          <div className="absolute top-0 h-28 w-28 shrink-0 -translate-y-1/2 overflow-hidden rounded-full border border-black">
            {/* eslint-disable-next-line @next/next/no-img-element */}
            <img
              className="object-cover"
              src="/logo-ike-consertos-3.png"
              alt="Logo do Ike Consertos"
            />
          </div>
          <div className="mb-4 flex flex-col items-center">
            <h1 className="text-3xl font-black">IKE CONSERTOS</h1>
            <h2 className="text-2xl font-semibold text-neutral-800">
              vendas e consertos de celular
            </h2>
            <h3 className="text-lg font-semibold tracking-wider text-neutral-800">
              @ike.cell
            </h3>
            <p className="italic text-neutral-700">
              Faço consertos e vendas de celular na região de Canudos/NH 🧉
            </p>
          </div>
          <div className="flex w-full flex-col gap-4 text-white">
            <div className="relative">
              {/* <div className="absolute inset-0 z-10 h-full w-full translate-x-2 translate-y-2 rounded-md bg-black" /> */}
              <a
                href="https://api.whatsapp.com/send?phone=555189071588&text=Oi,%20gostaria%20de%20fazer%20um%20or%C3%A7amento,%20me%20chamo%20"
                target="_blank"
              >
                <button className="relative z-20 flex w-full grow items-center justify-center rounded-md bg-white bg-gradient-to-r from-green-500 to-green-400 p-4">
                  <i className="absolute left-4 top-1/2 -translate-y-1/2">
                    <Whatsapp width={32} height={32} />
                  </i>
                  <span className="block">Whatsapp</span>
                </button>
              </a>
            </div>
            <div className="relative">
              {/* <div className="absolute inset-0 z-10 h-full w-full translate-x-1.5 translate-y-1.5 rounded-md bg-gradient-to-l from-pink-600 to-violet-600" /> */}
              <a href="https://www.instagram.com/ike.cell" target="_blank">
                <button className="relative z-20 flex w-full grow items-center justify-center rounded-md bg-white bg-gradient-to-r from-orange-400 via-pink-500 to-violet-500 p-4">
                  <i className="absolute left-4 top-1/2 -translate-y-1/2">
                    <Instagram width={32} height={32} />
                  </i>
                  <span className="block">Instagram</span>
                </button>
              </a>
            </div>
            <div className="relative">
              {/* <div className="absolute inset-0 z-10 h-full w-full translate-x-1.5 translate-y-1.5 rounded-md bg-gradient-to-l from-blue-700 to-blue-900" /> */}
              <a href="https://www.facebook.com/profile.php?id=100090579578848" target="_blank">
                <button className="relative z-20 flex w-full grow items-center justify-center rounded-md bg-white bg-gradient-to-r from-blue-700 to-blue-500 p-4">
                  <i className="absolute left-4 top-1/2 -translate-y-1/2">
                    <Facebook width={32} height={32} />
                  </i>
                  <span className="block">Facebook</span>
                </button>
              </a>
            </div>
          </div>
        </div>
      </main>
    </>
  );
};

export default Home;
